name: check-pull-requests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.sha }}

jobs:
  check:
    name: Check Pull Requests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v3

      - name: Setup Node.js 🟩
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "22"

      - name: Install Dependencies 📦
        run: pnpm install

      - name: Check 🚨
        run: pnpm check
